on: [push]

jobs:   
  create_sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9   
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./BackEnd/requirements.txt
          
      - name: Generate Python SBOM
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: /BackEnd/requirements.txt
          output: ./bom.json
          format: json