on: [push]

jobs:   
  create_sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Python SBOM
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: ./backend/requirements.txt
          output: ./bom.json
          format: json