on:
  push:
    branches:
      - main
      - dev
      - 'feat/**'

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkoutcode
        uses: actions/checkout@v4
      
      - name: Create vulnerabilities directory
        run: mkdir vulnerabilities
      
      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run dependency-check
        run: npx dependency-check ./frontend/package.json --verbose

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: vulnerabilities
          path: vulnerabilities